### ISSUE TITLE
Json::List – items: [] or items: {}

### ISSUE THREAD

**Issue by Strech** [razum2um/lurker#80]
По спецификации, если указать списку, что `items` у него `{}` или `[]` это означает «что угодно», а не объект или массив.

Сдедующие примеры должны парситься и дампиться эдентично:

``` yml

---
foo:
  type: array
  items: []
bar:
  type: array
  items: {}
```

Так же есть проблемы с операцией `merge!` и `replace!` если `items` — что угодно.
