### ISSUE TITLE
Different empty example handling

### ISSUE THREAD

**Issue by Strech** [razum2um/lurker#86]
For generation process:

```yaml
description: ''
type: string
example:<white space>
```

For modification process:

```yaml
description: ''
type: string
example: ''
```
